services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Critico_de_bolsillo-app
    ports:
      - "8025:80"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: project-nginx_Critico_de_bolsillo
    ports:
      - "9000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - app

  db:
    image: mariadb:10.2.33
    container_name: Critico_de_bolsillo_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Critico_de_bolsillo
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_Critico_de_bolsillo
    environment:
      PMA_HOST: Critico_de_bolsillo_db
      MYSQL_ROOT_PASSWORD: secret
    command: sh -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && apache2-foreground"
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel-network

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhogCritico_de_bolsillo
    ports:
      - "1025:1025"
      - "8030:8030"
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge